#!/usr/bin/env python3

from hw_device_mgr.mgr_ros_hal.mgr import (
    ROSHALHWDeviceMgr,
    SimROSEtherCATHWDeviceMgr,
)
import sys
import os

if __name__ == "__main__":
    sim = os.environ.get("USE_SIM", "0").lower() in ("1", "true")
    if sim:
        mgr = SimROSEtherCATHWDeviceMgr(sim=True)
    else:
        mgr = ROSHALHWDeviceMgr()
    mgr.init(sys.argv)
    if sim:
        mgr.init_sim()
    mgr.init_devices()
    mgr.run()
